# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import userena.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_profile', 'Can view profile'),)},
        ),
        migrations.AddField(
            model_name='customer',
            name='mugshot',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot'),
        ),
        migrations.AddField(
            model_name='customer',
            name='privacy',
            field=models.CharField(choices=[(b'open', 'Open'), (b'registered', 'Registered'), (b'closed', 'Closed')], default=b'registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy'),
        ),
    ]
