# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_bank', '0004_remove_movie_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, upload_to='movie_picture'),
        ),
    ]
