# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_bank', '0007_auto_20181105_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(default='media/movie_picture/no-image-icon-4.png', upload_to='movie_picture'),
        ),
    ]
